"""Generate lean_src/PhononSeries.lean: the series reversion and density of states behind
Godfrin et al. PRB 103, 104516 Eq. (22), stated in an arbitrary commutative ring with a nilpotent
element (e^8 = 0, resp. e^9 = 0) -- i.e. in truncated power series -- and proved in stages so that every
`linear_combination` certificate stays small. The certificates are computed here; Lean checks them.
After regenerating, run `python3 scripts/regen_axiom_audit.py` to re-append the axiom-audit block."""
import sympy as sp

a1, a2, a3, a4, a5, a6, e = sp.symbols("a1 a2 a3 a4 a5 a6 e")
AL = [a1, a2, a3, a4, a5, a6]

def lean(expr):
    s = sp.sstr(sp.expand(expr)).replace("**", "^")
    return s

def trunc(p, n):
    P = sp.Poly(sp.expand(p), e)
    return sum(P.coeff_monomial(e**i) * e**i for i in range(n)), sp.expand(sum(P.coeff_monomial(e**i) * e**(i - n) for i in range(n, P.degree() + 1)))

def revert(alphas, order):
    bs = sp.symbols("b1:%d" % order); k = sp.symbols("k")
    ks = sum(b * e**(i + 1) for i, b in enumerate(bs))
    uk = sp.expand((k * (1 + sum(a * k**(i + 1) for i, a in enumerate(alphas)))).subs(k, ks))
    sol = {}
    for n in range(1, order):
        eq = uk.coeff(e, n).subs(sol) - (1 if n == 1 else 0)
        sol[bs[n - 1]] = sp.expand(sp.solve(eq, bs[n - 1])[0])
    return sp.expand(ks.subs(sol))

out = []
w = out.append
w('''/-
  PhononSeries.lean -- the algebra behind the phonon specific-heat series of
  Godfrin, Beauvois, Sultan, Krotscheck, Dawidowski, Faak, Ollivier, Sokol, PRB 103, 104516 (2021), Eq. (22).

  GENERATED by exploration/godfrin/gen_phonon_series_lean.py -- the `linear_combination` certificates are
  computed by computer algebra and CHECKED here by the kernel; nothing is trusted from the generator.

  Setting: an arbitrary commutative ring `R` with an element `e` such that `e ^ 8 = 0` (resp. `e ^ 9 = 0`).
  Taking R = A[[u]]/(u^8) this is exactly "equality of power series up to O(u^8)", without any analysis.

  * `dispersion_kInv`      -- the inverse series PRINTED in the paper (alpha_1 general, through (w/c)^7,
                              including the coefficient eta) really does invert
                              eps = c k (1 + a1 k + ... + a6 k^6)  modulo e^8.
  * `density_of_states`    -- for alpha_1 = 0:  k^2 dk/de  =  e^2 - 5 a2 e^4 - 6 a3 e^5 + 7(4 a2^2 - a4) e^6
                              + 8(9 a2 a3 - a5) e^7 - 3(55 a2^3 - 30 a2 a4 - 15 a3^2 + 3 a6) e^8   modulo e^9.
                              These are, up to the Bose-integral factors, the brackets in C, D, E, K, L.

  NOT proved here: that the term-by-term integral is an asymptotic expansion of the true C_V (a Watson-lemma
  statement about the real dispersion curve), and the assembly with `BoseIntegral.bose_integral_nat`.
-/
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

set_option linter.unusedVariables false  -- uniform signatures are intentional

namespace QuantumFluids.PhononSeries

variable {R : Type*} [CommRing R]
''')

# ---------- part 1: reversion, alpha_1 general, mod e^8
N = 8
kinv = revert(AL, N)
w("/-- The inverse series as printed in the paper (source lines 1359-1372), with `e = ω/c`. -/")
w(f"def kInv (a1 a2 a3 a4 a5 a6 e : R) : R :=\n  {lean(kinv)}\n")
pows = {1: kinv}
sizes = []
for j in range(2, 8):
    t, r = trunc(pows[j - 1] * kinv, N)
    pows[j] = t
    sizes.append(len(r.as_ordered_terms()))
    w(f"/-- `kInv ^ {j}` truncated at `e ^ 8`. -/")
    w(f"def kPow{j} (a1 a2 a3 a4 a5 a6 e : R) : R :=\n  {lean(t)}\n")
    prev = "kInv a1 a2 a3 a4 a5 a6 e" if j == 2 else f"kPow{j-1} a1 a2 a3 a4 a5 a6 e"
    w(f"theorem kPow{j}_eq (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :\n    {prev} * kInv a1 a2 a3 a4 a5 a6 e = kPow{j} a1 a2 a3 a4 a5 a6 e := by\n  unfold kInv kPow{j}" + (f" kPow{j-1}" if j > 2 else "") + f"\n  linear_combination ({lean(r)}) * h\n")
total = sp.expand(sum((AL[i - 2] if i >= 2 else 1) * pows[i] for i in range(1, 8)))
assert sp.expand(total - e) == 0, total
w('''/-- **The printed inverse series inverts the dispersion relation modulo `e ^ 8`.**
`k (1 + a1 k + a2 k^2 + ... + a6 k^6) = e` with `k = kInv`, the powers being taken modulo `e ^ 8`. -/
theorem dispersion_kInv (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :
    kInv a1 a2 a3 a4 a5 a6 e * (1 + a1 * kInv a1 a2 a3 a4 a5 a6 e + a2 * kInv a1 a2 a3 a4 a5 a6 e ^ 2
      + a3 * kInv a1 a2 a3 a4 a5 a6 e ^ 3 + a4 * kInv a1 a2 a3 a4 a5 a6 e ^ 4
      + a5 * kInv a1 a2 a3 a4 a5 a6 e ^ 5 + a6 * kInv a1 a2 a3 a4 a5 a6 e ^ 6) = e := by
  have h2 := kPow2_eq a1 a2 a3 a4 a5 a6 e h
  have h3 := kPow3_eq a1 a2 a3 a4 a5 a6 e h
  have h4 := kPow4_eq a1 a2 a3 a4 a5 a6 e h
  have h5 := kPow5_eq a1 a2 a3 a4 a5 a6 e h
  have h6 := kPow6_eq a1 a2 a3 a4 a5 a6 e h
  have h7 := kPow7_eq a1 a2 a3 a4 a5 a6 e h
  have key : kInv a1 a2 a3 a4 a5 a6 e + a1 * kPow2 a1 a2 a3 a4 a5 a6 e + a2 * kPow3 a1 a2 a3 a4 a5 a6 e
      + a3 * kPow4 a1 a2 a3 a4 a5 a6 e + a4 * kPow5 a1 a2 a3 a4 a5 a6 e + a5 * kPow6 a1 a2 a3 a4 a5 a6 e
      + a6 * kPow7 a1 a2 a3 a4 a5 a6 e = e := by
    unfold kInv kPow2 kPow3 kPow4 kPow5 kPow6 kPow7
    ring
  set k := kInv a1 a2 a3 a4 a5 a6 e with hk
  have e2 : k ^ 2 = kPow2 a1 a2 a3 a4 a5 a6 e := by rw [← h2]; ring
  have e3 : k ^ 3 = kPow3 a1 a2 a3 a4 a5 a6 e := by rw [← h3, ← e2]; ring
  have e4 : k ^ 4 = kPow4 a1 a2 a3 a4 a5 a6 e := by rw [← h4, ← e3]; ring
  have e5 : k ^ 5 = kPow5 a1 a2 a3 a4 a5 a6 e := by rw [← h5, ← e4]; ring
  have e6 : k ^ 6 = kPow6 a1 a2 a3 a4 a5 a6 e := by rw [← h6, ← e5]; ring
  have e7 : k ^ 7 = kPow7 a1 a2 a3 a4 a5 a6 e := by rw [← h7, ← e6]; ring
  calc k * (1 + a1 * k + a2 * k ^ 2 + a3 * k ^ 3 + a4 * k ^ 4 + a5 * k ^ 5 + a6 * k ^ 6)
      = k + a1 * k ^ 2 + a2 * k ^ 3 + a3 * k ^ 4 + a4 * k ^ 5 + a5 * k ^ 6 + a6 * k ^ 7 := by ring
    _ = e := by rw [e2, e3, e4, e5, e6, e7]; exact key
''')

# ---------- part 2: density of states, alpha_1 = 0, mod e^9
M = 9
k0 = sp.expand(kinv.subs(a1, 0))
kd = sp.diff(k0, e)
w("/-- The inverse series for `alpha_1 = 0`, the case the paper's Eq. (22) treats. -/")
w(f"def kInv0 (a2 a3 a4 a5 a6 e : R) : R :=\n  {lean(k0)}\n")
w("/-- Its formal derivative with respect to `e`. -/")
w(f"def kInv0Deriv (a2 a3 a4 a5 a6 e : R) : R :=\n  {lean(kd)}\n")
sq, r2 = trunc(k0 * k0, M)
w("/-- `kInv0 ^ 2` truncated at `e ^ 9`. -/")
w(f"def kSq0 (a2 a3 a4 a5 a6 e : R) : R :=\n  {lean(sq)}\n")
w(f"theorem kSq0_eq (a2 a3 a4 a5 a6 e : R) (h : e ^ 9 = 0) :\n    kInv0 a2 a3 a4 a5 a6 e ^ 2 = kSq0 a2 a3 a4 a5 a6 e := by\n  unfold kInv0 kSq0\n  linear_combination ({lean(r2)}) * h\n")
g, rg = trunc(sq * kd, M)
gexp = e**2 - 5*a2*e**4 - 6*a3*e**5 + 7*(4*a2**2 - a4)*e**6 + 8*(9*a2*a3 - a5)*e**7 - 3*(55*a2**3 - 30*a2*a4 - 15*a3**2 + 3*a6)*e**8
assert sp.expand(g - gexp) == 0
sizes += [len(r2.as_ordered_terms()), len(rg.as_ordered_terms())]
w('''/-- **Density of states of the phonon branch, modulo `e ^ 9`.** The brackets are exactly those of the
paper's coefficients C (`a2`), D (`a3`), E (`4 a2^2 - a4`), K (`9 a2 a3 - a5`) and
L (`55 a2^3 - 30 a2 a4 - 15 a3^2 + 3 a6`); the absent `e ^ 3` term is the absent `B T^4`. -/
theorem density_of_states (a2 a3 a4 a5 a6 e : R) (h : e ^ 9 = 0) :
    kInv0 a2 a3 a4 a5 a6 e ^ 2 * kInv0Deriv a2 a3 a4 a5 a6 e
      = e ^ 2 - 5 * a2 * e ^ 4 - 6 * a3 * e ^ 5 + 7 * (4 * a2 ^ 2 - a4) * e ^ 6
        + 8 * (9 * a2 * a3 - a5) * e ^ 7
        - 3 * (55 * a2 ^ 3 - 30 * a2 * a4 - 15 * a3 ^ 2 + 3 * a6) * e ^ 8 := by
  rw [kSq0_eq a2 a3 a4 a5 a6 e h]
  unfold kSq0 kInv0Deriv''')
w(f"  linear_combination ({lean(rg)}) * h\n")
w("end QuantumFluids.PhononSeries")
open("lean_src/PhononSeries.lean", "w").write("\n".join(out) + "\n")
print("certificate sizes (terms):", sizes)
