import Lake
open Lake DSL

package quantumFluids

/-- Umbrella target: `import QuantumFluids` gives the whole library. -/
@[default_target]
lean_lib QuantumFluids

/-- Mathlib is PINNED to tag v4.34.0-rc2 (2026-09-19 migration, owner decision, to
align all streams on one toolchain and allow cross-stream integration; same
revision as the OpenAI NavierStokesAndEuler tree). Before the migration the pin
was 6d605ae1 (Lean 4.33.0-rc2), which matched MechanicaFluidorum's Gate 2; that
sibling is expected to follow. -/
require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "85e3a25e006c35636f0e53b0e9296caca2685bc0"  -- tag v4.34.0-rc2

@[default_target]
lean_lib QuantumFluidsShell

@[default_target]
lean_lib MadelungSplit

@[default_target]
lean_lib Duality

@[default_target]
lean_lib GPGalerkin

@[default_target]
lean_lib ShellHamiltonian

@[default_target]
lean_lib DualLength

@[default_target]
lean_lib RipsFloor

@[default_target]
lean_lib SigmaRule

@[default_target]
lean_lib VortexWinding

@[default_target]
lean_lib QuantizedCirculation

@[default_target]
lean_lib HeliumKinematics

@[default_target]
lean_lib BoseIntegral

@[default_target]
lean_lib PhononSeries

@[default_target]
lean_lib PhononSpecificHeat

@[default_target]
lean_lib ZeroSound

@[default_target]
lean_lib PhaseMixing

@[default_target]
lean_lib Villani

@[default_target]
lean_lib WassersteinCertificate

@[default_target]
lean_lib Fricke

@[default_target]
lean_lib QHFricke

@[default_target]
lean_lib TopologicalProtection

/-- The OpenAI Navier-Stokes/Euler formalisation (Apache-2.0), pinned to the commit whose four
headline theorems MechanicaFluidorum audited to footprint
`{propext, Classical.choice, Quot.sound}`. Both trees are on Lean 4.34.0-rc2 and Mathlib
85e3a25, which is what makes the import possible; before the 2026-09-19 toolchain migration the
version skew blocked it. Only `NavierStokes.ProblemStatement` is imported (by `MadelungNSE`),
and it depends on two Mathlib modules, so the build cost is small. -/
require NavierStokesAndEuler from git
  "https://github.com/openai/NavierStokesAndEuler.git" @ "8937a8f4cbc7abaab5e9e97d1cc7f5d2319d9538"

@[default_target]
lean_lib MadelungNSE

/-- Comparator challenge statements (generated by scripts/make_comparator_challenges.py).
NOT a default target: they contain `sorry` by design and must never count as built theorems.
Built on demand by `comparator`, which names the module in its JSON config. -/
lean_lib ComparatorChallenges where
  globs := #[.submodules `ComparatorChallenges]
