import Lake
open Lake DSL

package quantumFluids

/-- Umbrella target: `import QuantumFluids` gives the whole library. -/
@[default_target]
lean_lib QuantumFluids

@[default_target]
lean_lib QuantumFluidsShell

@[default_target]
lean_lib MadelungSplit

@[default_target]
lean_lib Duality

@[default_target]
lean_lib GPGalerkin

@[default_target]
lean_lib ShellHamiltonian

@[default_target]
lean_lib DualLength

@[default_target]
lean_lib RipsFloor

@[default_target]
lean_lib SigmaRule

@[default_target]
lean_lib VortexWinding

@[default_target]
lean_lib QuantizedCirculation

@[default_target]
lean_lib HeliumKinematics

@[default_target]
lean_lib BoseIntegral

@[default_target]
lean_lib PhononSeries

@[default_target]
lean_lib PhononSpecificHeat

@[default_target]
lean_lib ZeroSound

@[default_target]
lean_lib PhaseMixing

@[default_target]
lean_lib Villani

@[default_target]
lean_lib WassersteinCertificate

@[default_target]
lean_lib MatchingScreening

@[default_target]
lean_lib KTFlow

@[default_target]
lean_lib DissipativeVortexDynamics

@[default_target]
lean_lib EinsteinRelation

@[default_target]
lean_lib PairPolarisation

@[default_target]
lean_lib QuasiPeriodicBound

@[default_target]
lean_lib Fricke

@[default_target]
lean_lib QHFricke

@[default_target]
lean_lib TopologicalProtection

@[default_target]
lean_lib ScaleResolvedWinding

@[default_target]
lean_lib ContinuumWinding

@[default_target]
lean_lib SectorTemperature

@[default_target]
lean_lib CompactBoson

@[default_target]
lean_lib ChargeLattice

@[default_target]
lean_lib SectorDuality

@[default_target]
lean_lib RCFTDuality

@[default_target]
lean_lib LevelRankDuality

/-- The OpenAI Navier-Stokes/Euler formalisation (Apache-2.0), pinned to the commit whose four
headline theorems MechanicaFluidorum audited to footprint
`{propext, Classical.choice, Quot.sound}`. That tree is itself on Lean 4.34.0-rc2 / Mathlib 85e3a25;
since the 2026-10-11 alignment of this library to Lean 4.34.1 it is built here against Mathlib v4.34.1
(the whole dependency graph, 8999 jobs, builds without source changes). Only `NavierStokes.ProblemStatement`
is imported (by `MadelungNSE`), and it depends on two Mathlib modules, so the build cost is small. -/
require NavierStokesAndEuler from git
  "https://github.com/openai/NavierStokesAndEuler.git" @ "8937a8f4cbc7abaab5e9e97d1cc7f5d2319d9538"

@[default_target]
lean_lib MadelungNSE

/-- Mathlib is PINNED to tag v4.34.1 (commit d13f23b7), the pin of the `openai/math` project and of the LeanMaster
contributions (2026-10-11 alignment, owner instruction "align to the last lean toolchain version"; the library was
rebuilt without any source change: 38 modules, 257 `#print axioms` statements, all within
`{propext, Classical.choice, Quot.sound}`). Before this it was tag v4.34.0-rc2 (85e3a25, the 2026-09-19 migration,
same revision as the OpenAI NavierStokesAndEuler tree) and, before that, 6d605ae1 (Lean 4.33.0-rc2). Declared last so
that Mathlib's versions of the shared dependencies take precedence (Lake's advice). -/
require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "v4.34.1"  -- tag v4.34.1 = d13f23b7

/-- Comparator challenge statements (generated by scripts/make_comparator_challenges.py).
NOT a default target: they contain `sorry` by design and must never count as built theorems.
Built on demand by `comparator`, which names the module in its JSON config. -/
lean_lib ComparatorChallenges where
  globs := #[.submodules `ComparatorChallenges]
