/-
  PhaseMixing.lean -- free transport forgets its initial density: the linear, field-free core of
  Landau damping.

  CONTEXT, so this is not mistaken for more than it is.  J. Bedrossian, *Formalization of Landau damping
  in the Vlasov-Poisson equations in Lean*, arXiv:2609.16801 (2026), formalizes the nonlinear
  Mouhot-Villani theorem.  What is below is a corollary of Mathlib's Riemann-Lebesgue lemma and is
  subsumed by that work.  It is here because the closed form `maxwellian_mode` is the known answer that
  this repository's Vlasov solver and plasma-echo test are validated against
  (src/quantumfluids/kinetic, pre-registration K3a), and a known answer should be a checked one.

  * `transport_solution`  -- f(t,x,v) = e^{ik(x - vt)} g(v) solves  ∂ₜf + v ∂ₓf = 0.
  * `phase_mixing`        -- its density mode  ∫ g(v) e^{-ikvt} dv → 0  as t → ∞, for k ≠ 0, with NO
                             regularity assumed on g (if g is not integrable the integral is 0 by
                             convention and the statement is vacuous; for integrable g it is the content).
  * `maxwellian_mode`     -- for the unit Maxwellian the mode is exactly e^{-k²t²/2}: Gaussian, not
                             exponential, decay -- free streaming is not Landau damping.
-/
import Mathlib

open Real Filter Topology MeasureTheory Complex

namespace QuantumFluids.PhaseMixing

theorem transport_solution (k v : ℝ) (gv : ℂ) (t x : ℝ) :
    HasDerivAt (fun t => cexp ((k * (x - v * t) : ℝ) * I) * gv)
        (-(v : ℂ) * ((k : ℂ) * I * (cexp ((k * (x - v * t) : ℝ) * I) * gv))) t ∧
    HasDerivAt (fun x => cexp ((k * (x - v * t) : ℝ) * I) * gv)
        ((k : ℂ) * I * (cexp ((k * (x - v * t) : ℝ) * I) * gv)) x := by
  constructor
  · have h := ((((hasDerivAt_id' t).const_mul v).const_sub x).const_mul k).ofReal_comp.mul_const I
    exact ((h.cexp).mul_const gv).congr_deriv (by push_cast; ring)
  · have h := ((((hasDerivAt_id' x).sub_const (v * t)).const_mul k).ofReal_comp).mul_const I
    exact ((h.cexp).mul_const gv).congr_deriv (by push_cast; ring)

/-- **Phase mixing.** The `k`-th density mode of free transport tends to zero. -/
theorem phase_mixing (g : ℝ → ℂ) {k : ℝ} (hk : k ≠ 0) :
    Tendsto (fun t : ℝ => ∫ v : ℝ, cexp (-((k * v * t : ℝ) : ℂ) * I) * g v) atTop (𝓝 0) := by
  have hRL := Real.tendsto_integral_exp_smul_cocompact g
  have hw : Tendsto (fun t : ℝ => k * t / (2 * π)) atTop (cocompact ℝ) := by
    rcases lt_or_gt_of_ne hk with hneg | hpos
    · refine Tendsto.mono_right ?_ atBot_le_cocompact
      have : Tendsto (fun t : ℝ => k / (2 * π) * t) atTop atBot :=
        tendsto_id.const_mul_atTop_of_neg (by have := pi_pos; exact div_neg_of_neg_of_pos hneg (by positivity))
      refine this.congr (fun t => by ring)
    · refine Tendsto.mono_right ?_ atTop_le_cocompact
      have : Tendsto (fun t : ℝ => k / (2 * π) * t) atTop atTop :=
        tendsto_id.const_mul_atTop (by have := pi_pos; positivity)
      refine this.congr (fun t => by ring)
  refine (hRL.comp hw).congr (fun t => ?_)
  simp only [Function.comp]
  congr 1; funext v
  rw [Circle.smul_def, Real.fourierChar_apply, smul_eq_mul]
  congr 2
  have : π ≠ 0 := pi_ne_zero
  push_cast; field_simp

/-- **The Maxwellian mode.** For `f₀(v) = e^{-v²/2}/√(2π)` the `k`-th density mode of free transport is
exactly `e^{-k²t²/2}`. This is the Gaussian in the ballistic-echo formula the solver is tested against. -/
theorem maxwellian_mode (k t : ℝ) :
    ∫ v : ℝ, cexp (-((k * v * t : ℝ) : ℂ) * I) * ((rexp (-v ^ 2 / 2) / √(2 * π) : ℝ) : ℂ)
      = cexp (-((k * t) ^ 2 / 2 : ℝ)) := by
  have hb : 0 < ((1 / 2 : ℂ)).re := by norm_num
  have h := fourierIntegral_gaussian hb (-(k * t : ℝ) : ℂ)
  have hs : 0 < √(2 * π) := sqrt_pos.mpr (by positivity)
  have hcp : ((π : ℂ) / (1 / 2)) ^ (1 / 2 : ℂ) = ((√(2 * π) : ℝ) : ℂ) := by
    rw [show ((π : ℂ) / (1 / 2)) = ((2 * π : ℝ) : ℂ) by push_cast; ring,
      Real.sqrt_eq_rpow, Complex.ofReal_cpow (by positivity)]
    norm_num
  rw [hcp] at h
  have hfun : (fun v : ℝ => cexp (-((k * v * t : ℝ) : ℂ) * I) * ((rexp (-v ^ 2 / 2) / √(2 * π) : ℝ) : ℂ))
      = fun v : ℝ => (cexp (I * (-(k * t : ℝ) : ℂ) * v) * cexp (-(1 / 2 : ℂ) * v ^ 2)) * ((√(2 * π) : ℝ) : ℂ)⁻¹ := by
    funext v
    push_cast
    rw [div_eq_mul_inv, ← mul_assoc]
    congr 2 <;> ring_nf
  rw [hfun, integral_mul_const, h]
  have hne : ((√(2 * π) : ℝ) : ℂ) ≠ 0 := by exact_mod_cast hs.ne'
  rw [mul_comm, ← mul_assoc, inv_mul_cancel₀ hne, one_mul]
  congr 1
  push_cast
  ring

end QuantumFluids.PhaseMixing

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
#print axioms QuantumFluids.PhaseMixing.transport_solution
#print axioms QuantumFluids.PhaseMixing.phase_mixing
#print axioms QuantumFluids.PhaseMixing.maxwellian_mode
