/-
# QuantumFluids — a Lean 4 library of machine-checked quantum-fluid structure

    import QuantumFluids

brings in everything below. Built against Lean 4.34.0-rc2 and Mathlib `85e3a25` (tag v4.34.0-rc2).
Every theorem carries a `#print axioms` line, generated by `scripts/regen_axiom_audit.py`, and the
whole set is re-checked by Comparator against two independent kernels.

**Status, stated up front.** These are correct proofs of results that are, in the main, either
already in the literature or forced by dimensional analysis — see `RETRACTIONS.md`. The value here
is as *verification infrastructure* for quantum-fluid work, not as new physics. Modules that may be
useful to others in their own right are marked (*).

| module | contents |
|---|---|
| `VortexWinding` (*) | correctness of phase-winding vortex detection: the loop sum is exactly an integer multiple of `2π`, edges cancel except at a phase difference of exactly `π`, and that failure case characterised |
| `QuantizedCirculation` (*) | circulation around a closed loop is `q · κ` with `κ = h/m`; no fraction of a quantum, and the quantum is attained |
| `HeliumKinematics` (*) | the identities a neutron-scattering analysis of superfluid ⁴He leans on: three-phonon decay open iff dispersion anomalous, two-roton momentum range `[0, 2k_R]`, calibration-invariance of any comparison with `2Δ_R`, time-of-flight formula equivalence, Landau critical velocity, `c² = dP/dρ` for Abraham's equation of state, Debye mode counting |
| `GPGalerkin` (*) | truncated Gross–Pitaevskii on any finite mode set: `Q = Σ_q |A_q|² ≥ 0`, mass and energy algebra, the Hamiltonian gradient identity |
| `MadelungSplit` | `|∇ψ|² = |∇a|² + a²|∇S|²` — the quantum-pressure / hydrodynamic split |
| `MadelungNSE` | the same objects in the OpenAI Navier–Stokes vocabulary; `∇·(∇φ) = Δφ` in their formalism |
| `DualLength` | the `ℓ(k) = ε²/(ħ²c²k³)` algebra, its floor and structure-factor form (significance retracted; see `RETRACTIONS.md` R2) |
| `QuantumFluidsShell`, `ShellHamiltonian`, `SigmaRule` | the complexified dyadic shell model: energy conservation, the cubic invariant, and which dispersive order controls which norm (novelty retracted; see R1) |
| `Duality` | `R + α'/R ≥ 2√(α')` and instances |
| `RipsFloor` | minimum separation ⇒ an edgeless Rips graph below it (the TDA bridge; homology itself is *not* formalised) |
-/

import VortexWinding
import QuantizedCirculation
import GPGalerkin
import MadelungSplit
import MadelungNSE
import DualLength
import QuantumFluidsShell
import ShellHamiltonian
import SigmaRule
import Duality
import RipsFloor
import HeliumKinematics
