/-
# QuantumFluids — a Lean 4 library of machine-checked quantum-fluid structure

    import QuantumFluids

brings in everything below. Built against Lean 4.34.0-rc2 and Mathlib `85e3a25` (tag v4.34.0-rc2).
Every theorem carries a `#print axioms` line, generated by `scripts/regen_axiom_audit.py`, and the
whole set is re-checked by Comparator against two independent kernels.

**Status, stated up front.** These are correct proofs of results that are, in the main, either
already in the literature or forced by dimensional analysis — see `RETRACTIONS.md`. The value here
is as *verification infrastructure* for quantum-fluid work, not as new physics. Modules that may be
useful to others in their own right are marked (*).

| module | contents |
|---|---|
| `VortexWinding` (*) | correctness of phase-winding vortex detection: the loop sum is exactly an integer multiple of `2π`, edges cancel except at a phase difference of exactly `π`, and that failure case characterised |
| `QuantizedCirculation` (*) | circulation around a closed loop is `q · κ` with `κ = h/m`; no fraction of a quantum, and the quantum is attained |
| `HeliumKinematics` (*) | the identities a neutron-scattering analysis of superfluid ⁴He leans on: three-phonon decay open iff dispersion anomalous, two-roton momentum range `[0, 2k_R]`, calibration-invariance of any comparison with `2Δ_R`, time-of-flight formula equivalence, Landau critical velocity, `c² = dP/dρ` for Abraham's equation of state, Debye mode counting |
| `BoseIntegral` (*) | `∫₀^∞ t^{s-1}/(eᵗ−1) = Γ(s)ζ(s)` via Mathlib's Mellin machinery, `∫₀^∞ t³/(eᵗ−1) = π⁴/15`, and the Debye `T³` specific heat with the coefficient used in the ⁴He literature |
| `PhononSeries` (*) | the inverse series printed in Godfrin et al., PRB 103, 104516 really inverts the phonon dispersion modulo `e⁸` (α₁ general), and the density of states modulo `e⁹`; stated in any commutative ring with a nilpotent element, with certificates computed by computer algebra and checked by the kernel |
| `PhononSpecificHeat` (*) | `B₆, B₈, B₁₀`, `ζ(6), ζ(8), ζ(10)`, the thermal Bose integral at every order, and all six coefficients A, C, D, E, K, L of their Eq. (22) — confirmed, no discrepancy |
| `ZeroSound` (*) | undamped zero sound in a Fermi liquid exists iff `F₀ˢ > 0`, in 3D (logarithmic response) and in 2D (algebraic response, explicit root `(1+F)/√(1+2F)`) — textbook physics, now checked; the 2D case is the one relevant to ³He films |
| `PhaseMixing` | free transport: the solution, decay of every density mode (Riemann–Lebesgue), and the Maxwellian closed form `e^{-k²t²/2}` the Vlasov solver is tested against. **Subsumed by** Bedrossian, arXiv:2609.16801, which formalizes nonlinear Landau damping |
| `Villani` (*) | Ollivier-Villani, arXiv:1011.4779, Theorem 1 at K=0: `#A * #B ≤ (#M)^2` for the midpoint set M of nonempty A, B in the Hamming cube -- the injection A×B ↪ M×M by crossover coding; plus a 3-line corollary of Mathlib's own Markov-kernel Data Processing Inequality (discrete H-theorem) |
| `WassersteinCertificate` (*) | finite LP weak duality for an assignment problem (any cost matrix, any finite index types): a feasible, tight dual certifies a matching optimal without searching the others. Instantiated on the closed-loop project's hand-verified toy example (`docs/designs/CLOSED_LOOP_PREREG.md` C1): the found matching is optimal at cost exactly 7/4; the broken C3 potential is shown infeasible |
| `GPGalerkin` (*) | truncated Gross–Pitaevskii on any finite mode set: `Q = Σ_q |A_q|² ≥ 0`, mass and energy algebra, the Hamiltonian gradient identity |
| `MadelungSplit` | `|∇ψ|² = |∇a|² + a²|∇S|²` — the quantum-pressure / hydrodynamic split |
| `MadelungNSE` | the same objects in the OpenAI Navier–Stokes vocabulary; `∇·(∇φ) = Δφ` in their formalism |
| `DualLength` | the `ℓ(k) = ε²/(ħ²c²k³)` algebra, its floor and structure-factor form (significance retracted; see `RETRACTIONS.md` R2) |
| `QuantumFluidsShell`, `ShellHamiltonian`, `SigmaRule` | the complexified dyadic shell model: energy conservation, the cubic invariant, and which dispersive order controls which norm (novelty retracted; see R1) |
| `Duality` | `R + α'/R ≥ 2√(α')` and instances |
| `RipsFloor` | minimum separation ⇒ an edgeless Rips graph below it (the TDA bridge; homology itself is *not* formalised) |
-/

import VortexWinding
import QuantizedCirculation
import GPGalerkin
import MadelungSplit
import MadelungNSE
import DualLength
import QuantumFluidsShell
import ShellHamiltonian
import SigmaRule
import Duality
import RipsFloor
import HeliumKinematics
import BoseIntegral
import PhononSeries
import PhononSpecificHeat
import ZeroSound
import PhaseMixing
import Villani
import WassersteinCertificate
import Fricke
import QHFricke
import TopologicalProtection
import ScaleResolvedWinding
import ContinuumWinding
import SectorTemperature
import CompactBoson
