"""Shared code of the chapter-5 computations (no plotting here).

Physics.  The projected Gross-Pitaevskii equation of the Rust engine `qf_pgpe` (hbar = m = 1, mean density n0 = 1,
contact coupling g, so the sound speed is c = sqrt(g n0)) has the exact small-amplitude spectrum of Bogoliubov,
    omega(k) = sqrt( c^2 k^2 + (k^2/2)^2 ),
which is `QuantumFluids.BogoliubovDispersion.bogEps c 1 k` of book/lean/Ch05_BogoliubovDispersion.lean.

Measurement.  A *broadband pulse*: the uniform condensate psi = 1 plus a weak random complex amplitude eta*xi_k in
EVERY retained mode k (|xi_k| ~ 1).  The field is then evolved and, at regular sample times t_j, the amplitude of
every mode is recorded in the *condensate frame*,
        s_k(t_j) = c_k(t_j) * conj(c_0(t_j)) / |c_0(t_j)|              (c_0 = amplitude of the k = 0 mode),
which removes the global phase exp(-i mu t) of the condensate (mu = g n0).  In the linear regime
        s_k(t) = alpha_k exp(-i w_k t) + beta_k exp(+i w_k t)
exactly (a normal-mode pair +-k).  `fit_omega` finds w_k by variable projection: for each trial w the two complex
amplitudes are solved by linear least squares and the residual is minimised over w.
"""
from __future__ import annotations
import numpy as np
from scipy.optimize import minimize_scalar


def bog(k, g=1.0, n0=1.0):
    """Bogoliubov frequency, hbar = m = 1:  omega^2 = c^2 k^2 + k^4/4,  c^2 = g n0."""
    k = np.asarray(k, dtype=float)
    return np.sqrt(g * n0 * k ** 2 + (k ** 2 / 2.0) ** 2)


def mode_set(eng, N):
    """Boolean mask (N, N) of the retained modes, read off the engine itself (not recomputed), and the wavevectors."""
    rng = np.random.default_rng(12345)
    probe = (rng.normal(size=(N, N)) + 1j * rng.normal(size=(N, N)))
    m = np.asarray(eng.modes(probe)) != 0
    assert int(m.sum()) == eng.n_modes, (int(m.sum()), eng.n_modes)
    return m


def wavevectors(N, L):
    k1 = 2 * np.pi * np.fft.fftfreq(N, d=L / N)
    kx, ky = np.meshgrid(k1, k1, indexing="ij")
    return kx, ky


def initial_pulse(eng, N, eta, seed):
    """Uniform condensate (psi = 1, c_0 = N^2) + eta * N^2 * xi_k on every retained mode k != 0 (xi complex normal)."""
    rng = np.random.default_rng(seed)
    mask = mode_set(eng, N)
    c = np.array(eng.uniform(), dtype=complex)
    xi = (rng.normal(size=(N, N)) + 1j * rng.normal(size=(N, N))) / np.sqrt(2.0)
    add = eta * N ** 2 * xi * mask
    add[0, 0] = 0.0
    return c + add, mask


def record_condensate_frame(run_step, c0, mask, n_samples, N, keep_lab=None):
    """Advance with `run_step(c) -> c` (one sample interval) and record s_k = c_k conj(c_0)/|c_0| / N^2 for k in mask.
    Returns array (n_samples, n_modes) complex128 (row 0 = initial state) and, if `keep_lab` is a (ix, iy) pair,
    the lab-frame amplitude c_k/N^2 of that single mode (to show the global phase)."""
    c = c0
    nm = int(mask.sum())
    out = np.empty((n_samples, nm), dtype=np.complex128)
    lab = np.empty(n_samples, dtype=np.complex128) if keep_lab is not None else None
    for j in range(n_samples):
        if j > 0:
            c = run_step(c)
        c = np.asarray(c)
        ph = np.conj(c[0, 0]) / abs(c[0, 0])
        out[j] = c[mask] * ph / N ** 2
        if lab is not None:
            lab[j] = c[keep_lab] / N ** 2
    return out, lab


def _resid_vec(w, t, S, S2):
    """Variable-projection residual of the fit  alpha e^{-i w t} + beta e^{+i w t}  for each column of S at its own
    trial frequency w (shape (nm,)).  S2 = sum |s|^2 per column.  Closed-form 2x2 normal equations.  The exponentials are
    generated by the recurrence e_{j+1} = e_j exp(-i w dt) (uniform sampling), renormalised every 64 steps, which is
    ~10x cheaper than evaluating a complex exponential for every (sample, mode)."""
    n = len(t)
    dt = t[1] - t[0]
    z = np.exp(-1j * w * dt)
    e = np.exp(-1j * w * t[0])
    b1 = np.zeros_like(z); b2 = np.zeros_like(z); P = np.zeros_like(z)
    for j in range(n):
        ce = np.conj(e)
        sj = S[j]
        b1 += ce * sj
        b2 += e * sj
        P += ce * ce
        e = e * z
        if j % 64 == 63:
            e = e / np.abs(e)
    det = n * n - np.abs(P) ** 2
    th1 = (n * b1 - P * b2) / det
    th2 = (-np.conj(P) * b1 + n * b2) / det
    expl = (np.conj(b1) * th1 + np.conj(b2) * th2).real
    return S2 - expl, th1, th2


def prony_omega(t, S):
    """One-shot estimate of w for every column.  A series  s_j = alpha z^j + beta z^-j  (z = e^{-i w dt}) obeys
    s_{j+1} + s_{j-1} = 2 cos(w dt) s_j ; the least-squares coefficient is  gamma = sum conj(s_j)(s_{j+1}+s_{j-1}) / sum |s_j|^2."""
    dt = t[1] - t[0]
    mid = S[1:-1]
    num = np.sum(np.conj(mid) * (S[2:] + S[:-2]), axis=0).real
    den = np.sum(np.abs(mid) ** 2, axis=0)
    gam = np.clip(num / den, -2.0, 2.0)
    return np.arccos(gam / 2.0) / dt


def fit_columns(t, S, iters=26, width_bins=0.15):
    """Frequency w > 0 of the pair e^{-iwt}, e^{+iwt} in every column of the complex series S (n, nm).
    Start: `prony_omega`.  Then vectorised golden-section minimisation of the variable-projection residual in
    +-width_bins FFT bins around the start (one residual evaluation per iteration).
    Returns (w, rel_resid, |beta|/|alpha|)."""
    n, nm = S.shape
    dt = t[1] - t[0]
    T = n * dt
    w0 = prony_omega(t, S)
    half = width_bins * 2 * np.pi / T
    a = np.maximum(w0 - half, 1e-6)
    b = w0 + half
    S2 = np.sum(np.abs(S) ** 2, axis=0)
    gr = (np.sqrt(5.0) - 1.0) / 2.0
    c = b - gr * (b - a)
    d = a + gr * (b - a)
    fc = _resid_vec(c, t, S, S2)[0]
    fd = _resid_vec(d, t, S, S2)[0]
    for _ in range(iters):
        left = fc < fd                                   # minimum lies in [a, d]
        # case left:  new b = d, new d = c, new c = b - gr (b - a); evaluate only the new c
        # case right: new a = c, new c = d, new d = a + gr (b - a); evaluate only the new d
        a_n = np.where(left, a, c)
        b_n = np.where(left, d, b)
        c_n = np.where(left, b_n - gr * (b_n - a_n), d)
        d_n = np.where(left, c, a_n + gr * (b_n - a_n))
        fc_n_old = np.where(left, np.nan, fd)            # value at new c if right (old d)
        fd_n_old = np.where(left, fc, np.nan)            # value at new d if left  (old c)
        trial = np.where(left, c_n, d_n)
        ft = _resid_vec(trial, t, S, S2)[0]
        fc = np.where(left, ft, fc_n_old)
        fd = np.where(left, fd_n_old, ft)
        a, b, c, d = a_n, b_n, c_n, d_n
    w = 0.5 * (a + b)
    r, th1, th2 = _resid_vec(w, t, S, S2)
    rel = np.sqrt(np.maximum(r, 0.0) / np.maximum(S2, 1e-300))
    ratio = np.abs(th2) / np.maximum(np.abs(th1), 1e-300)
    return w, rel, ratio


def fit_all(t, S, split=True, iters=26):
    """Fit every column; optionally also the two halves of the record separately (a model-free error proxy)."""
    w, rel, ratio = fit_columns(t, S, iters)
    out = dict(omega=w, rel_resid=rel, beta_over_alpha=ratio, omega_prony=prony_omega(t, S))
    if split:
        h = len(t) // 2
        out["omega_first"] = fit_columns(t[:h], S[:h], iters)[0]
        out["omega_second"] = fit_columns(t[h:], S[h:], iters)[0]
    return out
