"""Chapter 10: writes figures/ch10_audit_result.tex, the paragraph that reports the outcome of the environment audit, from facts/audit/*.json.
Every number in it is computed here from those files (and stored in figures/ch10_audit_text.json for the report).  Nothing is claimed that the files do not show:
if a module has no environment audit, or failed to compile, the paragraph says so by name.
Run:  .venv/bin/python book/figures/ch10_audit_text.py"""
import sys, json, re
from pathlib import Path
here = Path(__file__).resolve().parent; BOOK = here.parent
sys.path.insert(0, str(BOOK))
import importlib.util
spec = importlib.util.spec_from_file_location("ma", BOOK / "facts/make_appA.py"); ma = importlib.util.module_from_spec(spec); spec.loader.exec_module(ma)
mods = sorted(f.stem for f in ma.SRC.glob("*.lean") if not f.name.startswith("_tmp") and f.name not in ("lakefile.lean", "QuantumFluids.lean"))
stale = [m for m in mods if (ma.AUD / f"{m}.json").exists() and not ma.audit_is_current(ma.AUD / f"{m}.json", ma.SRC / f"{m}.lean")]   # audited, then the CODE of the file changed
audit = {m: json.load(open(ma.AUD / f"{m}.json")) for m in mods if (ma.AUD / f"{m}.json").exists() and m not in stale}
ok = [m for m in mods if m in audit and audit[m]["exit"] == 0 and audit[m]["errors"] == 0 and audit[m].get("audit")]
bad = [m for m in mods if m in audit and m not in ok]
todo = [m for m in mods if m not in audit and m not in stale]
fp_only = [m for m in todo if (ma.audit_of(m) or {}).get("firstpass")]            # a clean first-pass compile log (the author's own #print axioms lines) is on file
nothing = [m for m in todo if m not in fp_only]
STD = {"propext", "Classical.choice", "Quot.sound"}
decl = sum(1 for m in ok for t in audit[m]["theorems"] if t["line"] >= 0); auto = sum(1 for m in ok for t in audit[m]["theorems"] if t["line"] < 0)
src = sum(audit[m]["source"]["theorem_decls"] for m in ok)
sorry = [m for m in ok if audit[m]["audit"]["sorryAx"]]; userax = [m for m in ok if audit[m]["audit"]["axiom_decls"]]; nonstd = [m for m in ok if set(audit[m]["audit"]["union_axioms"]) - STD]
classes = {}
for m in ok:
    for t in audit[m]["theorems"]:
        if t["line"] < 0: continue
        k = tuple(sorted(t["axioms"])); classes[k] = classes.get(k, 0) + 1
def name(k): return "no axiom" if not k else "propext only" if k == ("propext",) else "propext and Quot.sound" if k == ("Quot.sound", "propext") else "all three" if set(k) == STD else "+".join(k)
cl = {name(k): v for k, v in sorted(classes.items(), key=lambda kv: -kv[1])}
lspec = importlib.util.spec_from_file_location("la", BOOK / "facts/lean_audit.py"); la = importlib.util.module_from_spec(lspec); lspec.loader.exec_module(la)
mism = {}
for m in ok:
    mt = la.match_source(m, audit[m])                                   # current rule: theorems generated by Lean (no source position) are not compared
    if mt["source_unmatched"] or mt["env_not_in_source"]: mism[m] = mt
# the extra-over-generator finding: theorems in the sources that carry no author-written audit line although the module has some
unaudited_by_author = {m: audit[m]["source"]["theorem_decls"] - audit[m]["source"]["print_axioms_lines"] for m in ok if audit[m]["source"]["print_axioms_lines"] and audit[m]["source"]["theorem_decls"] != audit[m]["source"]["print_axioms_lines"]}
t = []
_oth = (([f"compile failed: {', '.join(bad)}"] if bad else []) + ([f"the audit on file was made on an earlier version of the source, so it does not count: {', '.join(stale)}"] if stale else []) +
        ([f"only a first-pass compile log is on file (the author's own \\texttt{{\\#print axioms}} lines, no error, no \\texttt{{sorry}}): {', '.join(fp_only)}"] if fp_only else []) +
        ([f"nothing usable is on file: {', '.join(nothing)}"] if nothing else []))
t.append(f"We audited \\emph{{{len(ok)}}} of the {len(mods)} modules at environment level" + ("" if not _oth else f" (the others --- {'; '.join(_oth)})") + ". ")
t.append(f"They declare {decl} theorem constants with a source position, against {src} \\texttt{{theorem}} or \\texttt{{lemma}} keywords in their sources"
         + (f", and Lean itself generated {auto} more, which have no source position (equation lemmas and the like)" if auto else "") + ". ")
if ok:
    t.append(f"{'No module' if not userax else str(len(userax)) + ' modules'} declares an axiom of its own, \\texttt{{sorryAx}} is reachable from "
             f"{'no constant of any of them' if not sorry else 'the constants of ' + ', '.join(sorry)}, and "
             f"{'every constant depends on at most' if not nonstd else 'the footprint of ' + ', '.join(nonstd) + ' leaves'} \\texttt{{propext}}, \\texttt{{Classical.choice}} and \\texttt{{Quot.sound}}. ")
    t.append("By the set of axioms a theorem depends on: " + "; ".join(f"{v} {'uses' if v == 1 else 'use'} {k}" for k, v in cl.items()) + ". ")
    if mism:
        # classify the theorem constants that have a source position but no theorem/lemma keyword; keywords with no constant would be a defect and are named
        extra = {m: [n for n in mt["env_not_in_source"] if n in {x["name"] for x in audit[m]["theorems"] if x["line"] >= 0}] for m, mt in mism.items()}
        missing = {m: mt["source_unmatched"] for m, mt in mism.items() if mt["source_unmatched"]}
        n_inst = sum(1 for m in extra for n in extra[m] if n.split(".")[-1].startswith("inst")); n_field = sum(len(v) for v in extra.values()) - n_inst
        t.append(f"The surplus of theorem constants over keywords is {sum(len(v) for v in extra.values())}: {n_field} proof-valued structure fields (such as \\texttt{{Balanced.invol}} of \\texttt{{VortexWinding}}), which Lean records as theorems, and "
                 f"{n_inst} instance whose value is a proof" + ("" if not missing else "; and a theorem keyword with no constant in " + ", ".join(missing)) + " (the lists are in \\texttt{facts/lean\\_audit.md}). ")
    else: t.append("Every theorem keyword of the sources of these modules corresponds to a theorem constant of the kernel environment, and the other way round. ")
    if unaudited_by_author:
        t.append("Modules whose author-written audit lines are fewer than their theorems: " + ", ".join(f"\\texttt{{{m}}} ({v} without)" for m, v in unaudited_by_author.items()) + ". ")
(here / "ch10_audit_result.tex").write_text("".join(t) + "\n")
# ---- the book's own Lean files (book/lean/*.lean), audited with `lean_audit.py --book`
def TT(m): return "\\texttt{" + m.replace("_", "\\_") + "}"
def TTs(ms): return ", ".join(TT(m) for m in ms)
bstems = la.book_stems()
bj = {m: json.load(open(ma.AUD / f"book_{m}.json")) for m in bstems if (ma.AUD / f"book_{m}.json").exists() and ma.audit_is_current(ma.AUD / f"book_{m}.json", ma.BL / f"{m}.lean")}
bok = [m for m in bstems if m in bj and bj[m]["exit"] == 0 and bj[m]["errors"] == 0 and bj[m].get("audit")]
bbad = [m for m in bstems if m in bj and m not in bok]
bnone = [m for m in bstems if m not in bj]
bsorry = [m for m in bok if bj[m]["audit"]["sorryAx"]]; buser = [m for m in bok if bj[m]["audit"]["axiom_decls"]]; bnon = [m for m in bok if set(bj[m]["audit"]["union_axioms"]) - STD]
bth = sum(1 for m in bok for x in bj[m]["theorems"] if x["line"] >= 0)
_imp = [m for m in bok if set(bj[m]["source"]["imports"]) - {"Mathlib"}]                      # book files that import library modules (resolved from the audit's own scratch builds)
_impl = "" if not _imp else f" (and, for {TTs(_imp)}, the library modules that the file imports, as built by the audit)"
if bstems and bok:
    bt = (f"The Lean files written for this book (the last section of appendix~\\ref{{appA}}) were audited the same way, each compiled against the pinned Mathlib{_impl}: \\emph{{{len(bok)}}} of {len(bstems)} files, "
          f"{bth} theorem constants. " + ("None declares" if not buser else f"{TTs(buser)} declare(s)") + " an axiom of its own; "
          + ("\\texttt{sorryAx} is reachable from no constant of any of them" if not bsorry else f"\\texttt{{sorryAx}} is reachable in {TTs(bsorry)}") + "; "
          + ("every constant depends on at most the three standard axioms" if not bnon else f"the footprint of {TTs(bnon)} leaves the three standard axioms") + ". "
          + ((f"Not covered: " + "; ".join(([f"compile failed: {TTs(bbad)}"] if bbad else []) + ([f"no current audit on file: {TTs(bnone)}"] if bnone else [])) + ". ") if (bbad or bnone) else ""))
elif bstems:
    bt = (f"The {len(bstems)} Lean files written for this book (the last section of appendix~\\ref{{appA}}) had not been audited at environment level when this text was generated: "
          "for them appendix~\\ref{appA} shows no audit status, and the only evidence is the \\texttt{\\#print axioms} lines at the end of each file, which this audit did not re-check. ")
else:
    bt = ""
# a deliberate negative control (a file that is meant to fail) is compiled expecting errors, listed apart and never counted
bcj = {m: json.load(open(ma.AUD / f"book_{m}.json")) for m in la.book_controls() if (ma.AUD / f"book_{m}.json").exists() and ma.audit_is_current(ma.AUD / f"book_{m}.json", ma.BL / f"{m}.lean")}
if la.book_controls() and not bcj:
    bt += (f"The file{'s' if len(la.book_controls()) > 1 else ''} " + ", ".join(f"\\texttt{{{m.replace('_', chr(92) + '_')}}}" for m in la.book_controls())
           + ", written to fail, " + ("is" if len(la.book_controls()) == 1 else "are") + " listed apart in appendix~\\ref{appA} and counted nowhere. ")
if bcj:
    good = [m for m, r in bcj.items() if r.get("as_expected")]; badc = [m for m in bcj if m not in good]
    names = ", ".join(f"\\texttt{{{m.replace('_', chr(92) + '_')}}}" for m in bcj)
    bt += (f"The file{'s' if len(bcj) > 1 else ''} {names}, written to fail and listed apart in appendix~\\ref{{appA}}, " + ("was" if len(bcj) == 1 else "were") + " compiled expecting errors: "
           + ("it failed, as intended" if len(good) == len(bcj) == 1 else f"{len(good)} of {len(bcj)} failed as intended") + (f"; {TTs(badc)} DID NOT FAIL, which is a defect of the control" if badc else "") + ". ")
(here / "ch10_audit_book.tex").write_text(bt + "\n")
# ---- the table of the modules that carry no audit line of their own --------------------------------------------------------------------------
noprint = [m for m in mods if audit.get(m) and audit[m]["source"]["print_axioms_lines"] == 0] + [m for m in mods if m not in audit and sum(1 for l in (ma.SRC / f"{m}.lean").read_text().split("\n") if l.startswith("#print axioms")) == 0]
rows = []
for m in noprint:
    a = audit.get(m)
    if a and a["exit"] == 0 and a["errors"] == 0 and a.get("audit"):
        decl = sum(1 for t in a["theorems"] if t["line"] >= 0)
        ordr = {"propext": 0, "Classical.choice": 1, "Quot.sound": 2}
        fp = ", ".join(x.replace("Classical.choice", "choice").replace("Quot.sound", "quot") for x in sorted(a["audit"]["union_axioms"], key=lambda x: (ordr.get(x, 9), x))) or "none"
        rows.append(f"\\texttt{{{m}}} & {decl} & {a['compile_s']:.0f} & {'no' if not a['audit']['sorryAx'] else 'YES'} & {fp} \\\\")
    elif a:
        rows.append(f"\\texttt{{{m}}} & -- & -- & -- & compile failed (exit {a['exit']}) \\\\")
    else:
        rows.append(f"\\texttt{{{m}}} & -- & -- & -- & not audited at environment level \\\\")
(here / "ch10_audit_seven.tex").write_text(
    "\\begin{table}[tbp]\\centering\\small\\renewcommand{\\arraystretch}{1.1}\\begin{tabular}{@{}lrrll@{}}\\toprule module & theorems & Lean s & \\texttt{sorryAx} & axioms used\\\\\\midrule\n"
    + "\n".join(rows) + "\n\\bottomrule\\end{tabular}\\caption{The modules whose sources carry no \\texttt{\\#print axioms} line, audited at environment level: theorem constants declared "
    "in the file, Lean wall time in seconds on the shared machine (load 8--35, so an indication only), whether \\texttt{sorryAx} is reachable, and the axioms used "
    "(\\texttt{choice} = \\texttt{Classical.choice}, \\texttt{quot} = \\texttt{Quot.sound}).}\\label{ch10:tab-seven}\\end{table}\n")

json.dump(dict(book_negative_controls={m: dict(exit=r["exit"], errors=r["errors"], as_expected=r.get("as_expected")) for m, r in bcj.items()}, book_files=bstems, book_ok=bok, book_failed=bbad, book_not_audited=bnone, book_theorem_constants=bth, modules=len(mods), env_ok=len(ok), failed=bad, stale=stale, first_pass_only=fp_only, nothing_usable=nothing, not_reached=todo, declared_theorems=decl, generated_by_lean=auto, source_theorem_keywords=src,
               sorry_modules=sorry, user_axiom_modules=userax, nonstandard_modules=nonstd, classes=cl, mismatches=list(mism), fewer_audit_lines_than_theorems=unaudited_by_author),
          open(here / "ch10_audit_text.json", "w"), indent=1)
print("".join(t))
