"""Helpers shared by the solution scripts of chapters 6-10 (Appendix C, files figures/sol06_*.py ... sol10_*.py).

(1) cvode_env(): identify the rusty_sundials module in use and REFUSE the stale build of the shared .venv (FACTS_ED2 section 2.4):
    Adams on y' = -y, t in [0, 10], rtol 1e-8, atol 1e-14 must need fewer than 5000 right-hand sides.  Run every script that uses
    CVODE with  PYTHONPATH=/mnt/data/xdev-cache/rs_py_5db8041:/mnt/data/xdev-cache/qf_ext .venv/bin/python ...
(2) Numbers: collects every number a solution quotes, with its source, and writes figures/solNN_numbers.json and the macro file
    figures/solNN_numbers.tex (one \\newcommand per number, prefix per chapter), so that the text cannot drift from the script.
    A script may own only some keys of a chapter's file: write() merges with the keys already on disk (its own keys replaced).
"""
from __future__ import annotations
import hashlib, json, math, re, time
from pathlib import Path

HERE = Path(__file__).resolve().parent
COMMIT_FIXED = "5db8041fd2e3840defcff2b4a8c26c1cbb2467fd"


def cvode_env():
    import rusty_sundials
    from rusty_sundials import CvodeSolver
    n = [0]

    def f(t, y):
        n[0] += 1
        return [-y[0]]
    s = CvodeSolver("adams", 1e-8, 1e-14, 5_000_000)
    _, y = s.solve(f, 0.0, [1.0], 10.0)
    err = abs(y[0] - math.exp(-10.0)) / math.exp(-10.0)
    path = Path(rusty_sundials.__file__).resolve()
    if ".venv" in str(path) or n[0] >= 5000:
        raise SystemExit(f"rusty_sundials at {path} is the stale build (Adams probe: {n[0]} right-hand sides); run with "
                         "PYTHONPATH=/mnt/data/xdev-cache/rs_py_5db8041:/mnt/data/xdev-cache/qf_ext")
    commit_f = path.parent / "commit.txt"
    commit = commit_f.read_text().strip() if commit_f.exists() else None
    if commit != COMMIT_FIXED:
        raise SystemExit(f"rusty_sundials at {path} reports commit {commit}, expected {COMMIT_FIXED}")
    return dict(module=str(path), sha256=hashlib.sha256(path.read_bytes()).hexdigest(), commit=commit,
                adams_probe_rhs_calls=n[0], adams_probe_relerr=err, date=time.strftime("%Y-%m-%d %H:%M"))


def fmt(x, digits=3, sci_below=1e-3, sci_above=1e5):
    """TeX text of a number: fixed notation with `digits` significant figures, or a x 10^n."""
    if x == 0:
        return "0"
    ax = abs(x)
    if ax < sci_below or ax >= sci_above:
        e = int(math.floor(math.log10(ax)))
        m = x / 10 ** e
        ms = f"{m:.{max(digits - 1, 0)}f}"
        if float(ms) in (10.0, -10.0):
            e += 1
            ms = f"{x / 10 ** e:.{max(digits - 1, 0)}f}"
        return f"{ms}\\times10^{{{e}}}"
    e = int(math.floor(math.log10(ax)))
    dec = max(digits - 1 - e, 0)
    return f"{x:.{dec}f}"


class Numbers:
    def __init__(self, nn: str, prefix: str, script: str):
        assert re.fullmatch(r"[A-Za-z]+", prefix)
        self.nn, self.prefix, self.script = nn, prefix, script
        self.macros: dict[str, dict] = {}
        self.data: dict[str, object] = {}

    def add(self, key: str, value, tex: str | None = None, source: str = "", digits: int = 3):
        assert re.fullmatch(r"[A-Za-z]+", key), key
        if tex is None:
            tex = fmt(float(value), digits)
        self.macros[key] = dict(tex=tex, value=value, source=source or self.script)
        return value

    def put(self, key: str, obj):
        self.data[key] = obj

    def write(self):
        jpath = HERE / f"sol{self.nn}_numbers.json"
        old = json.loads(jpath.read_text()) if jpath.exists() else {}
        macros = {k: v for k, v in old.get("macros", {}).items() if v.get("script") != self.script}
        for k, v in self.macros.items():
            v = dict(v)
            v["script"] = self.script
            macros[k] = v
        data = old.get("data", {})
        data[self.script] = self.data
        out = {"note": f"Every number quoted by chapters/sol{self.nn}.tex: macro \\{self.prefix}<key> = tex; value and source. "
                       f"Written by the scripts named in each entry (figures/sol_common.py).",
               "macros": dict(sorted(macros.items())), "data": data}
        jpath.write_text(json.dumps(out, indent=1, default=float))
        lines = [f"% generated by figures/sol_common.py from figures/sol{self.nn}_numbers.json -- do not edit"]
        for k, v in sorted(macros.items()):
            lines.append(f"\\newcommand{{\\{self.prefix}{k}}}{{{v['tex']}}}")
        (HERE / f"sol{self.nn}_numbers.tex").write_text("\n".join(lines) + "\n")
        print(f"wrote {jpath.name} ({len(macros)} macros)")
