/- GENERATED by scripts/make_comparator_challenges.py from lean_src/BoseIntegral.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
The Bose integral behind the phonon specific heat of superfluid helium.

[G21] = Godfrin et al., Phys. Rev. B 103, 104516 (2021), Eq. (22): the phonon specific heat is a
series `C_V = A T³ + C T⁵ + D T⁶ + …` whose coefficients come from Bose integrals
`∫₀^∞ tⁿ/(eᵗ − 1) dt = Γ(n+1) ζ(n+1)`. The paper remarks that earlier published versions of this
series "contain errors". This file machine-checks the integral that fixes the leading (Debye)
coefficient `A`, and states the general Mellin identity from which every other coefficient follows.

Mathlib has `ζ(4) = π⁴/90` and the Gamma integral, but not the Bose integral; the bridge is
`hasSum_mellin` applied to `1/(eᵗ − 1) = Σₙ e^{-(n+1)t}`.

`mellin F s` is, by definition, `∫ t in Ioi 0, t^(s-1) • F t`, so `mellin bose 4` IS
`∫₀^∞ t³/(eᵗ − 1) dt`.
-/

import Mathlib

namespace QuantumFluids.BoseIntegral

open Real Set

/-- The Bose factor `1/(eᵗ − 1)`, complex-valued so that Mathlib's `mellin` applies. -/
noncomputable def bose (t : ℝ) : ℂ := ((1 / (rexp t - 1) : ℝ) : ℂ)

/-- `1/(eᵗ − 1) = Σₙ e^{-(n+1)t}` for `t > 0`: the geometric series behind Bose statistics. -/
theorem hasSum_bose {t : ℝ} (ht : t ∈ Ioi (0 : ℝ)) :
    HasSum (fun n : ℕ => (1 : ℂ) * rexp (-((n : ℝ) + 1) * t)) (bose t) := by
  sorry
/-- **Mellin form of the Bose integral.** For `Re s > 1`,
`∫₀^∞ t^(s-1)/(eᵗ − 1) dt = Γ(s) · Σₙ 1/(n+1)^s`. -/
theorem hasSum_mellin_bose {s : ℂ} (hs : 1 < s.re) :
    HasSum (fun n : ℕ => Complex.Gamma s * 1 / (((n : ℝ) + 1 : ℝ) : ℂ) ^ s) (mellin bose s) := by
  sorry
/-- **`∫₀^∞ t³/(eᵗ − 1) dt = π⁴/15`.** This is `Γ(4) ζ(4) = 6 · π⁴/90`, the Bose integral behind the
Debye `T³` law and hence behind the leading coefficient `A = 2π²k_B⁴V/(15c³ħ³)` of [G21] Eq. (22). -/
theorem mellin_bose_four : mellin bose 4 = (π : ℂ) ^ 4 / 15 := by
  sorry
/-! ## From the integral to the coefficient `A` of [G21] Eq. (22)

For a pure phonon branch `ε = ħck` the substitution `x = ħck/k_BT` turns the internal energy
`(V/2π²) ∫ ε k² /(e^{ε/k_BT} − 1) dk` into `(V/2π²) (k_BT)⁴/(ħc)³ · ∫₀^∞ x³/(eˣ − 1) dx`. With the
value `π⁴/15` proved above, the energy is `π² V (k_BT)⁴ / (30 (ħc)³)`. The substitution itself is
not formalised here; what is checked is everything after it. -/

/-- Phonon internal energy after the substitution, with the Bose integral `I` left symbolic. -/
noncomputable def debyeEnergy (V kB hbar c I T : ℝ) : ℝ :=
  V / (2 * π ^ 2) * (kB * T) ^ 4 / (hbar * c) ^ 3 * I

/-- With `I = π⁴/15` the prefactor collapses to `π² V / 30`. -/
theorem debyeEnergy_eq (V kB hbar c T : ℝ) :
    debyeEnergy V kB hbar c (π ^ 4 / 15) T = π ^ 2 * V * (kB * T) ^ 4 / (30 * (hbar * c) ^ 3) := by
  sorry
/-- **The Debye coefficient.** `C_V = dE/dT = A T³` with `A = 2π² k_B⁴ V / (15 c³ ħ³)`, exactly
the coefficient **A** printed in [G21] Eq. (22). -/
theorem debye_specific_heat (V kB hbar c T : ℝ) :
    HasDerivAt (fun T => debyeEnergy V kB hbar c (π ^ 4 / 15) T)
      (2 * π ^ 2 * kB ^ 4 * V / (15 * c ^ 3 * hbar ^ 3) * T ^ 3) T := by
  sorry
end QuantumFluids.BoseIntegral

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
