/- GENERATED by scripts/make_comparator_challenges.py from lean_src/DualLength.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
import Mathlib

namespace QuantumFluids.DualLength

/-- `ℓ(k) = ε² / (hc² k³)`, the dual length, written with `ε²` as the argument since only the
square appears. -/
noncomputable def dualLength (hc k epsSq : ℝ) : ℝ := epsSq / (hc ^ 2 * k ^ 3)

/-- Bogoliubov: `ε² = (hc k)² + (hc k²/ks)²`, the Pythagorean sum of the phonon and
free-particle branches. -/
noncomputable def bogoliubovSq (hc ks k : ℝ) : ℝ := (hc * k) ^ 2 + (hc * k ^ 2 / ks) ^ 2

/-- The dual-scale shape `R + α'/R` with `R = 1/k` and `α' = 1/ks²`. -/
noncomputable def ell (ks k : ℝ) : ℝ := 1 / k + k / ks ^ 2

/-- **The phonon branch gives exactly `1/k`.** -/
theorem dualLength_phonon {hc k : ℝ} (hhc : hc ≠ 0) (hk : k ≠ 0) :
    dualLength hc k ((hc * k) ^ 2) = 1 / k := by
  sorry
/-- **The free-particle branch gives exactly `k/ks²`.** -/
theorem dualLength_free {hc ks k : ℝ} (hhc : hc ≠ 0) (hk : k ≠ 0) (hks : ks ≠ 0) :
    dualLength hc k ((hc * k ^ 2 / ks) ^ 2) = k / ks ^ 2 := by
  sorry
/-- **The dual length of the Bogoliubov dispersion is the `R + α'/R` form.** -/
theorem dualLength_bogoliubov {hc ks k : ℝ} (hhc : hc ≠ 0) (hk : k ≠ 0) (hks : ks ≠ 0) :
    dualLength hc k (bogoliubovSq hc ks k) = ell ks k := by
  sorry
/-- … and `ℓ` is invariant under it: the map exchanges the phonon and free-particle terms. -/
theorem ell_dual_invariant {ks k : ℝ} (hk : k ≠ 0) (hks : ks ≠ 0) :
    ell ks (ks ^ 2 / k) = ell ks k := by
  sorry
/-- **The dual-scale bound.** `ℓ(k) ≥ 2/ks` for every positive `k`: an effective length that
cannot go below `2/ks = ħ/(mc) = √2 ξ`. -/
theorem ell_ge {ks k : ℝ} (hk : 0 < k) (hks : 0 < ks) : 2 / ks ≤ ell ks k := by
  sorry
/-- **The bound is saturated exactly at the self-dual point** `k = ks`, the fixed point of the
involution. -/
theorem ell_eq_iff {ks k : ℝ} (hk : 0 < k) (hks : 0 < ks) : ell ks k = 2 / ks ↔ k = ks := by
  sorry
/-- **The falsification lemma.** If the measured dual length at some `k` is strictly below `2/ks`,
then the dispersion at that `k` is not Bogoliubov. This is the form in which the He-II data
(measured `ℓ/(2/ks) = 0.047` at the roton) refutes the dual-scale hypothesis for that fluid. -/
theorem not_bogoliubov_of_lt {hc ks k epsSq : ℝ} (hhc : hc ≠ 0) (hk : 0 < k) (hks : 0 < ks)
    (hmeas : dualLength hc k epsSq < 2 / ks) : epsSq ≠ bogoliubovSq hc ks k := by
  sorry
end QuantumFluids.DualLength
