/- GENERATED by scripts/make_comparator_challenges.py from lean_src/MadelungNSE.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
Bridge: the Madelung (quantum-fluid) velocity field expressed in OpenAI's Navier-Stokes vocabulary.

Imports `NavierStokes.ProblemStatement` from openai/NavierStokesAndEuler @ 8937a8f (Apache-2.0),
the same commit whose four headline theorems MechanicaFluidorum audited to footprint
`{propext, Classical.choice, Quot.sound}`. Both trees are on Lean 4.34.0-rc2 and Mathlib
85e3a25 (tag v4.34.0-rc2), which is what makes the import possible at all.

WHY THIS FILE. `MadelungSplit.lean` states the quantum-pressure/hydrodynamic split with
hand-rolled directional derivatives. The OpenAI tree already fixes Frechet-derivative vocabulary on
`EuclideanSpace R (Fin 3)` -- `spatialDerivative`, `spatialDivergence`, `pressureGradient`,
`spatialLaplacian` -- in which THEIR incompressible Navier-Stokes residual is written. Restating our
objects in that vocabulary means the quantum-fluid and Navier-Stokes sides are expressed in one
formalism and can be compared as mathematics rather than by analogy.

WHAT IS PROVED. `divergence_pressureGradient`: the divergence of their `pressureGradient` is the
scalar Laplacian. They never needed this (their pressure enters only as a gradient), so it is
genuinely added, and it is the identity that makes the Madelung continuity equation expressible in
their formalism. `divergence_madelungVelocity` then gives `div u = (hbar/m) * Laplacian S` for the
Madelung velocity `u = (hbar/m) grad S`.

WHAT IS NOT PROVED. No dynamics, no Gross-Pitaevskii equation, no claim about Navier-Stokes
regularity, and nothing about their blow-up theorems. Second differentiability of the phase is a
genuine HYPOTHESIS, and it is exactly what fails on a vortex line, where `S` is undefined.
-/

import NavierStokes.ProblemStatement
import Mathlib

namespace QuantumFluids.MadelungNSE

open NavierStokes.ProblemStatement

/-- The scalar Laplacian of a pressure-like field, in the same coordinate style as their
`spatialLaplacian` (which is the componentwise version for vector fields). -/
noncomputable def scalarLaplacian (p : PressureField) (t : ℝ) (x : Space) : ℝ :=
  ∑ i : Fin 3, fderiv ℝ (fun y : Space =>
    fderiv ℝ (fun z : Space => p (t, z)) y (coordinateVector i)) x (coordinateVector i)

/-- Second differentiability of the spatial field at a point: each first partial derivative is
again differentiable there. This is the hypothesis, and it is what fails at a vortex core. -/
def TwiceSpatial (p : PressureField) (t : ℝ) (x : Space) : Prop :=
  ∀ i : Fin 3, DifferentiableAt ℝ
    (fun y : Space => fderiv ℝ (fun z : Space => p (t, z)) y (coordinateVector i)) x

/-- **The divergence of their pressure gradient is the scalar Laplacian.**
`div (grad p) = Δp`, stated with their `spatialDivergence` and their `pressureGradient`. -/
theorem divergence_pressureGradient (p : PressureField) (t : ℝ) (x : Space)
    (h : TwiceSpatial p t x) :
    spatialDivergence (fun q : SpaceTime => pressureGradient p q.1 q.2) t x
      = scalarLaplacian p t x := by
  sorry
/-- The Madelung velocity field `u = (hbar/m) grad S`, in their `VelocityField` type. -/
noncomputable def madelungVelocity (hbar m : ℝ) (S : PressureField) : VelocityField :=
  fun q : SpaceTime => (hbar / m) • pressureGradient S q.1 q.2

/-- **Divergence of the Madelung velocity.** `div u = (hbar/m) * Laplacian S`, in their
vocabulary. With continuity this is the equation the quantum-pressure term acts against; here only
the kinematic identity is claimed. -/
theorem divergence_madelungVelocity (hbar m : ℝ) (S : PressureField) (t : ℝ) (x : Space)
    (h : TwiceSpatial S t x) :
    spatialDivergence (madelungVelocity hbar m S) t x = (hbar / m) * scalarLaplacian S t x := by
  sorry
end QuantumFluids.MadelungNSE

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
