/- GENERATED by scripts/make_comparator_challenges.py from lean_src/PhaseMixing.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
  PhaseMixing.lean -- free transport forgets its initial density: the linear, field-free core of
  Landau damping.

  CONTEXT, so this is not mistaken for more than it is.  J. Bedrossian, *Formalization of Landau damping
  in the Vlasov-Poisson equations in Lean*, arXiv:2609.16801 (2026), formalizes the nonlinear
  Mouhot-Villani theorem.  What is below is a corollary of Mathlib's Riemann-Lebesgue lemma and is
  subsumed by that work.  It is here because the closed form `maxwellian_mode` is the known answer that
  this repository's Vlasov solver and plasma-echo test are validated against
  (src/quantumfluids/kinetic, pre-registration K3a), and a known answer should be a checked one.

  * `transport_solution`  -- f(t,x,v) = e^{ik(x - vt)} g(v) solves  ∂ₜf + v ∂ₓf = 0.
  * `phase_mixing`        -- its density mode  ∫ g(v) e^{-ikvt} dv → 0  as t → ∞, for k ≠ 0, with NO
                             regularity assumed on g (if g is not integrable the integral is 0 by
                             convention and the statement is vacuous; for integrable g it is the content).
  * `maxwellian_mode`     -- for the unit Maxwellian the mode is exactly e^{-k²t²/2}: Gaussian, not
                             exponential, decay -- free streaming is not Landau damping.
-/
import Mathlib

open Real Filter Topology MeasureTheory Complex

namespace QuantumFluids.PhaseMixing

theorem transport_solution (k v : ℝ) (gv : ℂ) (t x : ℝ) :
    HasDerivAt (fun t => cexp ((k * (x - v * t) : ℝ) * I) * gv)
        (-(v : ℂ) * ((k : ℂ) * I * (cexp ((k * (x - v * t) : ℝ) * I) * gv))) t ∧
    HasDerivAt (fun x => cexp ((k * (x - v * t) : ℝ) * I) * gv)
        ((k : ℂ) * I * (cexp ((k * (x - v * t) : ℝ) * I) * gv)) x := by
  sorry
/-- **Phase mixing.** The `k`-th density mode of free transport tends to zero. -/
theorem phase_mixing (g : ℝ → ℂ) {k : ℝ} (hk : k ≠ 0) :
    Tendsto (fun t : ℝ => ∫ v : ℝ, cexp (-((k * v * t : ℝ) : ℂ) * I) * g v) atTop (𝓝 0) := by
  sorry
/-- **The Maxwellian mode.** For `f₀(v) = e^{-v²/2}/√(2π)` the `k`-th density mode of free transport is
exactly `e^{-k²t²/2}`. This is the Gaussian in the ballistic-echo formula the solver is tested against. -/
theorem maxwellian_mode (k t : ℝ) :
    ∫ v : ℝ, cexp (-((k * v * t : ℝ) : ℂ) * I) * ((rexp (-v ^ 2 / 2) / √(2 * π) : ℝ) : ℂ)
      = cexp (-((k * t) ^ 2 / 2 : ℝ)) := by
  sorry
end QuantumFluids.PhaseMixing

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
