/- GENERATED by scripts/make_comparator_challenges.py from lean_src/PhaseMixing.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
import Mathlib

open Real Filter Topology MeasureTheory Complex

namespace QuantumFluids.PhaseMixing

theorem transport_solution (k v : ℝ) (gv : ℂ) (t x : ℝ) :
    HasDerivAt (fun t => cexp ((k * (x - v * t) : ℝ) * I) * gv)
        (-(v : ℂ) * ((k : ℂ) * I * (cexp ((k * (x - v * t) : ℝ) * I) * gv))) t ∧
    HasDerivAt (fun x => cexp ((k * (x - v * t) : ℝ) * I) * gv)
        ((k : ℂ) * I * (cexp ((k * (x - v * t) : ℝ) * I) * gv)) x := by
  sorry
/-- **Phase mixing.** The `k`-th density mode of free transport tends to zero. -/
theorem phase_mixing (g : ℝ → ℂ) {k : ℝ} (hk : k ≠ 0) :
    Tendsto (fun t : ℝ => ∫ v : ℝ, cexp (-((k * v * t : ℝ) : ℂ) * I) * g v) atTop (𝓝 0) := by
  sorry
/-- **The Maxwellian mode.** For `f₀(v) = e^{-v²/2}/√(2π)` the `k`-th density mode of free transport is
exactly `e^{-k²t²/2}`. This is the Gaussian in the ballistic-echo formula the solver is tested against. -/
theorem maxwellian_mode (k t : ℝ) :
    ∫ v : ℝ, cexp (-((k * v * t : ℝ) : ℂ) * I) * ((rexp (-v ^ 2 / 2) / √(2 * π) : ℝ) : ℂ)
      = cexp (-((k * t) ^ 2 / 2 : ℝ)) := by
  sorry
end QuantumFluids.PhaseMixing

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
