/- GENERATED by scripts/make_comparator_challenges.py from lean_src/PhononSeries.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
  PhononSeries.lean -- the algebra behind the phonon specific-heat series of
  Godfrin, Beauvois, Sultan, Krotscheck, Dawidowski, Faak, Ollivier, Sokol, PRB 103, 104516 (2021), Eq. (22).

  GENERATED by exploration/godfrin/gen_phonon_series_lean.py -- the `linear_combination` certificates are
  computed by computer algebra and CHECKED here by the kernel; nothing is trusted from the generator.

  Setting: an arbitrary commutative ring `R` with an element `e` such that `e ^ 8 = 0` (resp. `e ^ 9 = 0`).
  Taking R = A[[u]]/(u^8) this is exactly "equality of power series up to O(u^8)", without any analysis.

  * `dispersion_kInv`      -- the inverse series PRINTED in the paper (alpha_1 general, through (w/c)^7,
                              including the coefficient eta) really does invert
                              eps = c k (1 + a1 k + ... + a6 k^6)  modulo e^8.
  * `density_of_states`    -- for alpha_1 = 0:  k^2 dk/de  =  e^2 - 5 a2 e^4 - 6 a3 e^5 + 7(4 a2^2 - a4) e^6
                              + 8(9 a2 a3 - a5) e^7 - 3(55 a2^3 - 30 a2 a4 - 15 a3^2 + 3 a6) e^8   modulo e^9.
                              These are, up to the Bose-integral factors, the brackets in C, D, E, K, L.

  NOT proved here: that the term-by-term integral is an asymptotic expansion of the true C_V (a Watson-lemma
  statement about the real dispersion curve), and the assembly with `BoseIntegral.bose_integral_nat`.
-/
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

set_option linter.unusedVariables false  -- uniform signatures are intentional

namespace QuantumFluids.PhononSeries

variable {R : Type*} [CommRing R]

/-- The inverse series as printed in the paper (source lines 1359-1372), with `e = ω/c`. -/
def kInv (a1 a2 a3 a4 a5 a6 e : R) : R :=
  132*a1^6*e^7 - 42*a1^5*e^6 - 330*a1^4*a2*e^7 + 14*a1^4*e^5 + 84*a1^3*a2*e^6 + 120*a1^3*a3*e^7 - 5*a1^3*e^4 + 180*a1^2*a2^2*e^7 - 21*a1^2*a2*e^5 - 28*a1^2*a3*e^6 - 36*a1^2*a4*e^7 + 2*a1^2*e^3 - 28*a1*a2^2*e^6 - 72*a1*a2*a3*e^7 + 5*a1*a2*e^4 + 6*a1*a3*e^5 + 7*a1*a4*e^6 + 8*a1*a5*e^7 - a1*e^2 - 12*a2^3*e^7 + 3*a2^2*e^5 + 7*a2*a3*e^6 + 8*a2*a4*e^7 - a2*e^3 + 4*a3^2*e^7 - a3*e^4 - a4*e^5 - a5*e^6 - a6*e^7 + e

/-- `kInv ^ 2` truncated at `e ^ 8`. -/
def kPow2 (a1 a2 a3 a4 a5 a6 e : R) : R :=
  -132*a1^5*e^7 + 42*a1^4*e^6 + 240*a1^3*a2*e^7 - 14*a1^3*e^5 - 56*a1^2*a2*e^6 - 72*a1^2*a3*e^7 + 5*a1^2*e^4 - 72*a1*a2^2*e^7 + 12*a1*a2*e^5 + 14*a1*a3*e^6 + 16*a1*a4*e^7 - 2*a1*e^3 + 7*a2^2*e^6 + 16*a2*a3*e^7 - 2*a2*e^4 - 2*a3*e^5 - 2*a4*e^6 - 2*a5*e^7 + e^2

theorem kPow2_eq (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :
    kInv a1 a2 a3 a4 a5 a6 e * kInv a1 a2 a3 a4 a5 a6 e = kPow2 a1 a2 a3 a4 a5 a6 e := by
  sorry
/-- `kInv ^ 3` truncated at `e ^ 8`. -/
def kPow3 (a1 a2 a3 a4 a5 a6 e : R) : R :=
  90*a1^4*e^7 - 28*a1^3*e^6 - 108*a1^2*a2*e^7 + 9*a1^2*e^5 + 21*a1*a2*e^6 + 24*a1*a3*e^7 - 3*a1*e^4 + 12*a2^2*e^7 - 3*a2*e^5 - 3*a3*e^6 - 3*a4*e^7 + e^3

theorem kPow3_eq (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :
    kPow2 a1 a2 a3 a4 a5 a6 e * kInv a1 a2 a3 a4 a5 a6 e = kPow3 a1 a2 a3 a4 a5 a6 e := by
  sorry
/-- `kInv ^ 4` truncated at `e ^ 8`. -/
def kPow4 (a1 a2 a3 a4 a5 a6 e : R) : R :=
  -48*a1^3*e^7 + 14*a1^2*e^6 + 32*a1*a2*e^7 - 4*a1*e^5 - 4*a2*e^6 - 4*a3*e^7 + e^4

theorem kPow4_eq (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :
    kPow3 a1 a2 a3 a4 a5 a6 e * kInv a1 a2 a3 a4 a5 a6 e = kPow4 a1 a2 a3 a4 a5 a6 e := by
  sorry
/-- `kInv ^ 5` truncated at `e ^ 8`. -/
def kPow5 (a1 a2 a3 a4 a5 a6 e : R) : R :=
  20*a1^2*e^7 - 5*a1*e^6 - 5*a2*e^7 + e^5

theorem kPow5_eq (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :
    kPow4 a1 a2 a3 a4 a5 a6 e * kInv a1 a2 a3 a4 a5 a6 e = kPow5 a1 a2 a3 a4 a5 a6 e := by
  sorry
/-- `kInv ^ 6` truncated at `e ^ 8`. -/
def kPow6 (a1 a2 a3 a4 a5 a6 e : R) : R :=
  -6*a1*e^7 + e^6

theorem kPow6_eq (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :
    kPow5 a1 a2 a3 a4 a5 a6 e * kInv a1 a2 a3 a4 a5 a6 e = kPow6 a1 a2 a3 a4 a5 a6 e := by
  sorry
/-- `kInv ^ 7` truncated at `e ^ 8`. -/
def kPow7 (a1 a2 a3 a4 a5 a6 e : R) : R :=
  e^7

theorem kPow7_eq (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :
    kPow6 a1 a2 a3 a4 a5 a6 e * kInv a1 a2 a3 a4 a5 a6 e = kPow7 a1 a2 a3 a4 a5 a6 e := by
  sorry
/-- **The printed inverse series inverts the dispersion relation modulo `e ^ 8`.**
`k (1 + a1 k + a2 k^2 + ... + a6 k^6) = e` with `k = kInv`, the powers being taken modulo `e ^ 8`. -/
theorem dispersion_kInv (a1 a2 a3 a4 a5 a6 e : R) (h : e ^ 8 = 0) :
    kInv a1 a2 a3 a4 a5 a6 e * (1 + a1 * kInv a1 a2 a3 a4 a5 a6 e + a2 * kInv a1 a2 a3 a4 a5 a6 e ^ 2
      + a3 * kInv a1 a2 a3 a4 a5 a6 e ^ 3 + a4 * kInv a1 a2 a3 a4 a5 a6 e ^ 4
      + a5 * kInv a1 a2 a3 a4 a5 a6 e ^ 5 + a6 * kInv a1 a2 a3 a4 a5 a6 e ^ 6) = e := by
  sorry
/-- The inverse series for `alpha_1 = 0`, the case the paper's Eq. (22) treats. -/
def kInv0 (a2 a3 a4 a5 a6 e : R) : R :=
  -12*a2^3*e^7 + 3*a2^2*e^5 + 7*a2*a3*e^6 + 8*a2*a4*e^7 - a2*e^3 + 4*a3^2*e^7 - a3*e^4 - a4*e^5 - a5*e^6 - a6*e^7 + e

/-- Its formal derivative with respect to `e`. -/
def kInv0Deriv (a2 a3 a4 a5 a6 e : R) : R :=
  -84*a2^3*e^6 + 15*a2^2*e^4 + 42*a2*a3*e^5 + 56*a2*a4*e^6 - 3*a2*e^2 + 28*a3^2*e^6 - 4*a3*e^3 - 5*a4*e^4 - 6*a5*e^5 - 7*a6*e^6 + 1

/-- `kInv0 ^ 2` truncated at `e ^ 9`. -/
def kSq0 (a2 a3 a4 a5 a6 e : R) : R :=
  -30*a2^3*e^8 + 7*a2^2*e^6 + 16*a2*a3*e^7 + 18*a2*a4*e^8 - 2*a2*e^4 + 9*a3^2*e^8 - 2*a3*e^5 - 2*a4*e^6 - 2*a5*e^7 - 2*a6*e^8 + e^2

theorem kSq0_eq (a2 a3 a4 a5 a6 e : R) (h : e ^ 9 = 0) :
    kInv0 a2 a3 a4 a5 a6 e ^ 2 = kSq0 a2 a3 a4 a5 a6 e := by
  sorry
/-- **Density of states of the phonon branch, modulo `e ^ 9`.** The brackets are exactly those of the
paper's coefficients C (`a2`), D (`a3`), E (`4 a2^2 - a4`), K (`9 a2 a3 - a5`) and
L (`55 a2^3 - 30 a2 a4 - 15 a3^2 + 3 a6`); the absent `e ^ 3` term is the absent `B T^4`. -/
theorem density_of_states (a2 a3 a4 a5 a6 e : R) (h : e ^ 9 = 0) :
    kInv0 a2 a3 a4 a5 a6 e ^ 2 * kInv0Deriv a2 a3 a4 a5 a6 e
      = e ^ 2 - 5 * a2 * e ^ 4 - 6 * a3 * e ^ 5 + 7 * (4 * a2 ^ 2 - a4) * e ^ 6
        + 8 * (9 * a2 * a3 - a5) * e ^ 7
        - 3 * (55 * a2 ^ 3 - 30 * a2 * a4 - 15 * a3 ^ 2 + 3 * a6) * e ^ 8 := by
  sorry
end QuantumFluids.PhononSeries

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
