/- GENERATED by scripts/make_comparator_challenges.py from lean_src/RipsFloor.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
import Mathlib

namespace QuantumFluids.RipsFloor

variable {E : Type*} [PseudoMetricSpace E] {ι : Type*}

/-- Two distinct indices are Rips-adjacent at scale `t` when their points are within `t`. -/
def Adj (X : ι → E) (t : ℝ) (i j : ι) : Prop := i ≠ j ∧ dist (X i) (X j) ≤ t

/-- `d` separates the configuration: distinct points are at least `d` apart. -/
def Separated (X : ι → E) (d : ℝ) : Prop := ∀ i j, i ≠ j → d ≤ dist (X i) (X j)

/-- **Below the separation the Rips graph is edgeless.** -/
theorem no_adj_of_lt {X : ι → E} {d t : ℝ} (hsep : Separated X d) (ht : t < d) (i j : ι) :
    ¬ Adj X t i j := by
  sorry
/-- **Every scale carrying an edge is at least the separation.** This is the floor: the set of
scales at which anything at all happens in the filtration is contained in `[d, ∞)`. -/
theorem le_of_adj {X : ι → E} {d t : ℝ} (hsep : Separated X d) (h : ∃ i j, Adj X t i j) : d ≤ t := by
  sorry
/-- The floor is attained, not merely a bound: at a witnessing pair the scale `d` does carry an
edge, so `d` is the least scale at which the Rips graph has one. -/
theorem isLeast_edge_scale {X : ι → E} {d : ℝ} (hsep : Separated X d)
    {a b : ι} (hab : a ≠ b) (hd : dist (X a) (X b) = d) :
    IsLeast {t : ℝ | ∃ i j, Adj X t i j} d := by
  sorry
/-- The hypothesis is not vacuous and the bound is not automatic: a configuration with two
coincident points has separation `0` and carries an edge at every nonnegative scale. -/
theorem separated_zero_of_not_injective {X : ι → E} : Separated X 0 := by
  sorry
end QuantumFluids.RipsFloor
