/- GENERATED by scripts/make_comparator_challenges.py from lean_src/Villani.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
  Villani.lean -- a foundation for formalizing Cédric Villani's work, offered as a tribute.

  * `card_sq_ge` -- **Ollivier and Villani, "A curved Brunn-Minkowski inequality on the discrete
    hypercube", arXiv:1011.4779, Theorem 1, the K = 0 case.** For nonempty A, B in the Hamming cube
    {0,1}^N with midpoint set M, `#A * #B ≤ (#M)^2`. FULLY PROVED, no `sorry`, by the injection
    A×B ↪ M×M the paper's Section 3 describes: a canonical choice of which half of the differing
    coordinates of a pair (a,b) comes from `a`, together with the complementary choice, is
    recoverable from the resulting pair of midpoints.

  * The full Theorem 1, with the curvature term K = 1/(2N), is NOT attempted: its proof needs
    concentration of measure in the symmetric group (the paper's Lemma 4 and Proposition 5, via a
    quotienting argument), machinery not built here. See
    `docs/designs/ZERO_SOUND_LANDAU_DAMPING_PROPOSAL.md` §7 for the open-target list this belongs to.

  * `klDiv_nonincreasing_to_invariant` -- a three-line corollary of Mathlib's own
    `MeasureTheory.klDiv_comp_right_le` (the Data Processing Inequality for a Markov kernel), for a
    measure invariant under that kernel: the modern relative-entropy form of Boltzmann's H-theorem
    for a Markov chain. NOT presented as a contribution -- the mathematical content is entirely
    Mathlib's `klDiv_comp_right_le`. Included because it is the discrete skeleton of the entropy
    methods Villani surveys in "H-theorem and beyond" (Boltzmann's Legacy, EMS 2008), and it connects
    this file to `ZeroSound.lean`'s Fermi-liquid kinetic theory inside one project.

  Not attempted: the continuous collisional Boltzmann H-theorem, hypocoercivity, log-Sobolev and
  Talagrand inequalities, the Lott-Villani-Sturm curvature-dimension condition, and Landau damping
  (linear: see `ZeroSound.lean`; nonlinear: formalized, sorry-free, by J. Bedrossian,
  arXiv:2609.16801, which this file does not duplicate).
-/
import Mathlib

open scoped Classical
open Finset

namespace QuantumFluids.Villani

variable {N : ℕ}

abbrev Cube (N : ℕ) := Fin N → Bool

/-- The coordinates where `a` and `b` differ. -/
def diff (a b : Cube N) : Finset (Fin N) := univ.filter (fun i => a i ≠ b i)

/-- The Hamming distance. -/
def dist (a b : Cube N) : ℕ := (diff a b).card

theorem mem_diff_iff {a b : Cube N} {i : Fin N} : i ∈ diff a b ↔ a i ≠ b i := by
  sorry
/-- The general metric definition of a midpoint (Ollivier-Villani, Section 1.1):
`d(m,a) + d(m,b) = d(a,b)`, and `d(m,a)` within `1` of `d(a,b)/2` (written without division). -/
def IsMidpoint (a b m : Cube N) : Prop :=
  dist m a + dist m b = dist a b ∧ 2 * dist m a ≤ dist a b + 1 ∧ dist a b ≤ 2 * dist m a + 1

/-- The midpoint set of two finite sets `A, B`. -/
noncomputable def midpointSet (A B : Finset (Cube N)) : Finset (Cube N) :=
  univ.filter (fun m => ∃ a ∈ A, ∃ b ∈ B, IsMidpoint a b m)

/-- `crossover c a b` takes `a`'s bit on `c` and `b`'s bit elsewhere: `φ_c(a,b)` in the paper. -/
def crossover (c : Finset (Fin N)) (a b : Cube N) : Cube N :=
  fun i => if i ∈ c then a i else b i

/-- `diff (crossover c a b) a = diff a b \ c`, for ANY `c` (no hypothesis needed). -/
theorem diff_crossover_left (c : Finset (Fin N)) (a b : Cube N) :
    diff (crossover c a b) a = diff a b \ c := by
  sorry
/-- `diff (crossover c a b) b = c`, given `c ⊆ diff a b`. -/
theorem diff_crossover_right {c : Finset (Fin N)} {a b : Cube N} (hc : c ⊆ diff a b) :
    diff (crossover c a b) b = c := by
  sorry
theorem dist_crossover_left (c : Finset (Fin N)) (a b : Cube N) :
    dist (crossover c a b) a = (diff a b \ c).card := by
  sorry
theorem dist_crossover_right {c : Finset (Fin N)} {a b : Cube N} (hc : c ⊆ diff a b) :
    dist (crossover c a b) b = c.card := by
  sorry
/-- Any `c ⊆ diff a b` with `c.card` within `1` of `dist a b / 2` gives a genuine midpoint. -/
theorem isMidpoint_crossover {c : Finset (Fin N)} {a b : Cube N} (hc : c ⊆ diff a b)
    (h1 : 2 * c.card ≤ dist a b + 1) (h2 : dist a b ≤ 2 * c.card + 1) :
    IsMidpoint a b (crossover c a b) := by
  sorry
/-! ### A canonical half of a finite subset of `Fin N`

`takeHalf s` is the set of the `s.card / 2` smallest elements of `s`, for the natural order on
`Fin N` -- a function of `s` alone, crucial for the reconstruction argument below. -/

def takeHalf (s : Finset (Fin N)) : Finset (Fin N) :=
  (univ : Finset (Fin (s.card / 2))).image
    (fun i => s.orderEmbOfFin rfl (Fin.castLE (Nat.div_le_self _ 2) i))

theorem takeHalf_subset (s : Finset (Fin N)) : takeHalf s ⊆ s := by
  sorry
theorem card_takeHalf (s : Finset (Fin N)) : (takeHalf s).card = s.card / 2 := by
  sorry
/-! ### The injection, and Theorem 1 at `K = 0` -/

/-- `takeHalf (diff a b)` has size within `1` of `dist a b / 2`, so it qualifies as a crossover. -/
theorem takeHalf_card_bounds (a b : Cube N) :
    2 * (takeHalf (diff a b)).card ≤ dist a b + 1 ∧
    dist a b ≤ 2 * (takeHalf (diff a b)).card + 1 := by
  sorry
/-- The pair of midpoints coded by the canonical half `takeHalf (diff a b)` and its complement:
`Φ_{c_r}(a,b) = (φ_{c_r}(a,b), φ_{c̄_r}(a,b))` in the paper's notation. -/
def encode (a b : Cube N) : Cube N × Cube N :=
  (crossover (takeHalf (diff a b)) a b, crossover (diff a b \ takeHalf (diff a b)) a b)

theorem encode_fst_isMidpoint (a b : Cube N) : IsMidpoint a b (encode a b).1 := by
  sorry
theorem encode_snd_isMidpoint (a b : Cube N) : IsMidpoint a b (encode a b).2 := by
  sorry
theorem encode_mem_midpointSet {A B : Finset (Cube N)} {a b : Cube N} (ha : a ∈ A) (hb : b ∈ B) :
    (encode a b).1 ∈ midpointSet A B ∧ (encode a b).2 ∈ midpointSet A B := by
  sorry
/-- **Recoverability**: `diff` of the two encoded midpoints equals `diff a b`, for ANY
`c ⊆ diff a b` and its complement, not just the canonical half. This is what makes `encode`
invertible: `r := d(a,b)` is read off as `d(m, m')`. -/
theorem diff_crossover_crossover_compl {c : Finset (Fin N)} {a b : Cube N} (hc : c ⊆ diff a b) :
    diff (crossover c a b) (crossover (diff a b \ c) a b) = diff a b := by
  sorry
/-- **`encode` is injective on pairs**: this is Theorem 1's Φ, and the whole content of the
K = 0 case. From `encode a b = encode a' b'`, both sides give `diff a b = diff m m' = diff a' b'`
(previous lemma), so `c := takeHalf (diff a b)` is the SAME finset used to build both encoded
pairs; reading off `a, b, a', b'` at each coordinate `i` by whether `i ∈ c`, `i ∈ diff a b \ c`,
or neither, gives `a = a'` and `b = b'` in every case. -/
theorem encode_injective {a b a' b' : Cube N} (h : encode a b = encode a' b') :
    a = a' ∧ b = b' := by
  sorry
/-- **Ollivier-Villani, Theorem 1, the `K = 0` case.** For nonempty `A, B` in the Hamming cube,
with `M` their midpoint set, `#A * #B ≤ (#M)²`. Proved via the injection
`(a, b) ↦ encode a b` from `A ×ˢ B` into `M ×ˢ M`. -/
theorem card_sq_ge (A B : Finset (Cube N)) :
    A.card * B.card ≤ (midpointSet A B).card * (midpointSet A B).card := by
  sorry
/-! ### A discrete H-theorem, from Mathlib's own Data Processing Inequality
(Flattened into this same namespace, not a sub-namespace `EntropyMethods`: `scripts/regen_axiom_audit.py`
only reads a file's FIRST `namespace` line and prefixes every theorem with it, the same class of
limitation as the LeanGraph #print-axioms bug found earlier in this project -- worked around here
rather than fixed, since fixing the script is out of scope for this file.) -/

open MeasureTheory ProbabilityTheory InformationTheory

variable {𝓧 : Type*} {m𝓧 : MeasurableSpace 𝓧}

/-- **A Markov chain's relative entropy to an invariant measure is nonincreasing.** The modern
relative-entropy form of Boltzmann's H-theorem for a Markov kernel, three lines from Mathlib's
`klDiv_comp_right_le`: apply the Data Processing Inequality to `μ` and the invariant `ν`, using
`κ ∘ₘ ν = ν` to keep the reference measure fixed. Not a contribution; see the file header. -/
theorem klDiv_nonincreasing_to_invariant (κ : Kernel 𝓧 𝓧) [IsMarkovKernel κ]
    (μ ν : Measure 𝓧) [IsFiniteMeasure μ] [IsFiniteMeasure ν] (hν : κ ∘ₘ ν = ν) :
    klDiv (κ ∘ₘ μ) ν ≤ klDiv μ ν := by
  sorry
end QuantumFluids.Villani

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
