/- GENERATED by scripts/make_comparator_challenges.py from lean_src/ZeroSound.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
  ZeroSound.lean -- when does a Fermi liquid support undamped zero sound?

  Landau's collisionless kinetic equation for a Fermi liquid with a single Landau parameter `F` (= F₀ˢ)
  has a collective mode of phase velocity `s · v_F` when  `1 + F · Ω(s) = 0`, with Ω the angular average
  of the free response.  The mode is undamped iff `s > 1` (outside the particle-hole continuum); for
  `s < 1` it is Landau-damped -- the same mechanism as in a plasma, with `F` in place of `1/k²`.

  * 3D (bulk ³He):      Ω(s) = 1 - (s/2) log((s+1)/(s-1)),  condition  (s/2) log((s+1)/(s-1)) - 1 = 1/F.
  * 2D (³He monolayer): Ω(s) = 1 - s/√(s²-1).

  PROVED: in both dimensions an undamped root `s > 1` exists **iff** `F > 0`; in 2D the root is explicit,
  `s = (1+F)/√(1+2F)`.  This is textbook physics (Baym & Pethick, *Landau Fermi-Liquid Theory*); what is
  new is only that it is machine-checked.  The 2D case is included because the neutron-scattering
  measurement of a zero-sound-like mode by Godfrin et al., Nature 483, 576 (2012), is on a 2D film, where
  the logarithmic 3D formula does not apply.

  NOT proved: uniqueness of the 3D root (needs strict monotonicity); anything about `F₁ˢ`, finite
  temperature, or the damped branch `s < 1`.
-/
import Mathlib

open Real Set

namespace QuantumFluids.ZeroSound

/-- `g(s) = (s/2) log((s+1)/(s-1)) - 1`; the 3D zero-sound condition is `g s = 1/F`. -/
noncomputable def g3 (s : ℝ) : ℝ := s / 2 * log ((s + 1) / (s - 1)) - 1

theorem g3_pos {s : ℝ} (hs : 1 < s) : 0 < g3 s := by
  sorry
theorem g3_le {s : ℝ} (hs : 1 < s) : g3 s ≤ 1 / (s - 1) := by
  sorry
theorem g3_ge {s : ℝ} (hs : 1 < s) : 1 / 2 * log (2 / (s - 1)) - 1 ≤ g3 s := by
  sorry
theorem continuousOn_g3 {a b : ℝ} (ha : 1 < a) : ContinuousOn g3 (Icc a b) := by
  sorry
/-- **Undamped zero sound in 3D exists iff the interaction is repulsive.** -/
theorem zero_sound_iff (F : ℝ) : (∃ s, 1 < s ∧ g3 s = 1 / F) ↔ 0 < F := by
  sorry
/-- **Undamped zero sound in 2D exists iff the interaction is repulsive**, and the root is explicit. -/
theorem zero_sound_2d_iff (F : ℝ) :
    (∃ s, 1 < s ∧ 1 + F * (1 - s / √(s ^ 2 - 1)) = 0) ↔ 0 < F := by
  sorry
where
  zero_sound_2d_root {F : ℝ} (hF : 0 < F) :
      1 < (1 + F) / √(1 + 2 * F) ∧
        1 + F * (1 - (1 + F) / √(1 + 2 * F) / √(((1 + F) / √(1 + 2 * F)) ^ 2 - 1)) = 0 := by
    have hq0 : 0 < 1 + 2 * F := by linarith
    have hq : 0 < √(1 + 2 * F) := sqrt_pos.mpr hq0
    have hq2 : √(1 + 2 * F) ^ 2 = 1 + 2 * F := sq_sqrt hq0.le
    have h1 : 1 < (1 + F) / √(1 + 2 * F) := by
      rw [lt_div_iff₀ hq, one_mul, sqrt_lt' (by linarith)]; nlinarith
    refine ⟨h1, ?_⟩
    have e : ((1 + F) / √(1 + 2 * F)) ^ 2 - 1 = (F / √(1 + 2 * F)) ^ 2 := by
      rw [div_pow, div_pow, hq2]; field_simp; ring
    rw [e, sqrt_sq (by positivity)]
    field_simp
    ring

end QuantumFluids.ZeroSound

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
